site_name: Krupnik
repo_url: https://github.com/yurikrupnik/first-rust-app
nav:
  - Home: index.md
  - About: about.md
  - 'User Guide':
    - 'Writing your docs': 'writing-your-docs.md'
    - 'Styling your docs': 'styling-your-docs.md'
#  - About: tauri-app/tauri-app/docs/about.md
#theme: readthedocs