name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 8
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 20
#          cache: 'pnpm'
      - run: bun install
      - uses: nrwl/nx-set-shas@v4
      - run: bun exec nx affected -t lint test build
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: pnpm exec nx affected -t container --prod
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: yurikrupnik
#          REGISTRY: europe-central2-docker.pkg.dev/shared-404221/container-repository
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm exec nx affected -t lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 8
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 20
#          cache: 'pnpm'
      - run: bun install
      - uses: nrwl/nx-set-shas@v4
      - run: bun exec nx affected -t build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm exec nx affected -t test